name: CI/CD
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up jdk 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Permission
        run : chmod +x gradlew

      - name : Run tests
        run : ./gradlew test
  build:
    needs: test
    if: girhub.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ screts.DOCKER_USERNAME }}
          password: ${{ screts.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          centext: .
          push: true
          tags: |
            ${{ screts.DOCKER_USERNAME }}/gallery-back:lastest
            ${{ screts.DOCKER_USERNAME }}/gallery-back:${{ github.sha }}